// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.23.4
// source: proto/common.query.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryTypeEnum_QueryType int32

const (
	QueryTypeEnum_QUERY_UNSPECIFIED QueryTypeEnum_QueryType = 0
	QueryTypeEnum_Select            QueryTypeEnum_QueryType = 1
	QueryTypeEnum_Update            QueryTypeEnum_QueryType = 2
	QueryTypeEnum_Delete            QueryTypeEnum_QueryType = 3
	QueryTypeEnum_Insert            QueryTypeEnum_QueryType = 4
	QueryTypeEnum_Inject            QueryTypeEnum_QueryType = 5 // 自定义逻辑
	QueryTypeEnum_SelectOne         QueryTypeEnum_QueryType = 6 // 只查找一个元素
)

// Enum value maps for QueryTypeEnum_QueryType.
var (
	QueryTypeEnum_QueryType_name = map[int32]string{
		0: "QUERY_UNSPECIFIED",
		1: "Select",
		2: "Update",
		3: "Delete",
		4: "Insert",
		5: "Inject",
		6: "SelectOne",
	}
	QueryTypeEnum_QueryType_value = map[string]int32{
		"QUERY_UNSPECIFIED": 0,
		"Select":            1,
		"Update":            2,
		"Delete":            3,
		"Insert":            4,
		"Inject":            5,
		"SelectOne":         6,
	}
)

func (x QueryTypeEnum_QueryType) Enum() *QueryTypeEnum_QueryType {
	p := new(QueryTypeEnum_QueryType)
	*p = x
	return p
}

func (x QueryTypeEnum_QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryTypeEnum_QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_query_proto_enumTypes[0].Descriptor()
}

func (QueryTypeEnum_QueryType) Type() protoreflect.EnumType {
	return &file_proto_common_query_proto_enumTypes[0]
}

func (x QueryTypeEnum_QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryTypeEnum_QueryType.Descriptor instead.
func (QueryTypeEnum_QueryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{0, 0}
}

type BindEnum_Bind int32

const (
	BindEnum_None     BindEnum_Bind = 0
	BindEnum_BindResp BindEnum_Bind = 1
)

// Enum value maps for BindEnum_Bind.
var (
	BindEnum_Bind_name = map[int32]string{
		0: "None",
		1: "BindResp",
	}
	BindEnum_Bind_value = map[string]int32{
		"None":     0,
		"BindResp": 1,
	}
)

func (x BindEnum_Bind) Enum() *BindEnum_Bind {
	p := new(BindEnum_Bind)
	*p = x
	return p
}

func (x BindEnum_Bind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindEnum_Bind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_query_proto_enumTypes[1].Descriptor()
}

func (BindEnum_Bind) Type() protoreflect.EnumType {
	return &file_proto_common_query_proto_enumTypes[1]
}

func (x BindEnum_Bind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindEnum_Bind.Descriptor instead.
func (BindEnum_Bind) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{10, 0}
}

type QueryTypeEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryTypeEnum) Reset() {
	*x = QueryTypeEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTypeEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTypeEnum) ProtoMessage() {}

func (x *QueryTypeEnum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTypeEnum.ProtoReflect.Descriptor instead.
func (*QueryTypeEnum) Descriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{0}
}

type DataQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *DataMapping `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *DataQuery) Reset() {
	*x = DataQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQuery) ProtoMessage() {}

func (x *DataQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQuery.ProtoReflect.Descriptor instead.
func (*DataQuery) Descriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{1}
}

func (x *DataQuery) GetQuery() *DataMapping {
	if x != nil {
		return x.Query
	}
	return nil
}

type QueryChain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query []*DataMapping `protobuf:"bytes,1426,rep,name=query,proto3" json:"query,omitempty"`
}

func (x *QueryChain) Reset() {
	*x = QueryChain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChain) ProtoMessage() {}

func (x *QueryChain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChain.ProtoReflect.Descriptor instead.
func (*QueryChain) Descriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryChain) GetQuery() []*DataMapping {
	if x != nil {
		return x.Query
	}
	return nil
}

type DataMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       QueryTypeEnum_QueryType `protobuf:"varint,1,opt,name=type,proto3,enum=eden.common.QueryTypeEnum_QueryType" json:"type,omitempty"`
	InjectName string                  `protobuf:"bytes,2,opt,name=inject_name,json=injectName,proto3" json:"inject_name,omitempty"` // inject_name 为插入自定义逻辑的位置
	Query      string                  `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`                             // 用于查询数据库的语句
	Args       []*DataBinding          `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`                               // 参数的绑定配置
	Resp       []*DataBinding          `protobuf:"bytes,5,rep,name=resp,proto3" json:"resp,omitempty"`                               // 返回值的绑定配置
}

func (x *DataMapping) Reset() {
	*x = DataMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMapping) ProtoMessage() {}

func (x *DataMapping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMapping.ProtoReflect.Descriptor instead.
func (*DataMapping) Descriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{3}
}

func (x *DataMapping) GetType() QueryTypeEnum_QueryType {
	if x != nil {
		return x.Type
	}
	return QueryTypeEnum_QUERY_UNSPECIFIED
}

func (x *DataMapping) GetInjectName() string {
	if x != nil {
		return x.InjectName
	}
	return ""
}

func (x *DataMapping) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *DataMapping) GetArgs() []*DataBinding {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *DataMapping) GetResp() []*DataBinding {
	if x != nil {
		return x.Resp
	}
	return nil
}

type DataBinding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // name 用于绑定参数映射，一般与 patten_from 组合，将参数信息与 SQL 变量建立绑定
	// Types that are assignable to PattenFrom:
	//
	//	*DataBinding_FromArg
	//	*DataBinding_FromResp
	//	*DataBinding_FromContext
	//	*DataBinding_FromQuery
	PattenFrom isDataBinding_PattenFrom `protobuf_oneof:"patten_from"`
	// Types that are assignable to PattenTo:
	//
	//	*DataBinding_ToArg
	//	*DataBinding_ToResp
	//	*DataBinding_ToContext
	PattenTo isDataBinding_PattenTo `protobuf_oneof:"patten_to"`
	Type     string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"` // type 一般用在 to_context 相关的操作，用于将查询的数据按照指定的类型保存到 context 中
}

func (x *DataBinding) Reset() {
	*x = DataBinding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBinding) ProtoMessage() {}

func (x *DataBinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBinding.ProtoReflect.Descriptor instead.
func (*DataBinding) Descriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{4}
}

func (x *DataBinding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *DataBinding) GetPattenFrom() isDataBinding_PattenFrom {
	if m != nil {
		return m.PattenFrom
	}
	return nil
}

func (x *DataBinding) GetFromArg() string {
	if x, ok := x.GetPattenFrom().(*DataBinding_FromArg); ok {
		return x.FromArg
	}
	return ""
}

func (x *DataBinding) GetFromResp() string {
	if x, ok := x.GetPattenFrom().(*DataBinding_FromResp); ok {
		return x.FromResp
	}
	return ""
}

func (x *DataBinding) GetFromContext() string {
	if x, ok := x.GetPattenFrom().(*DataBinding_FromContext); ok {
		return x.FromContext
	}
	return ""
}

func (x *DataBinding) GetFromQuery() string {
	if x, ok := x.GetPattenFrom().(*DataBinding_FromQuery); ok {
		return x.FromQuery
	}
	return ""
}

func (m *DataBinding) GetPattenTo() isDataBinding_PattenTo {
	if m != nil {
		return m.PattenTo
	}
	return nil
}

func (x *DataBinding) GetToArg() string {
	if x, ok := x.GetPattenTo().(*DataBinding_ToArg); ok {
		return x.ToArg
	}
	return ""
}

func (x *DataBinding) GetToResp() string {
	if x, ok := x.GetPattenTo().(*DataBinding_ToResp); ok {
		return x.ToResp
	}
	return ""
}

func (x *DataBinding) GetToContext() string {
	if x, ok := x.GetPattenTo().(*DataBinding_ToContext); ok {
		return x.ToContext
	}
	return ""
}

func (x *DataBinding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type isDataBinding_PattenFrom interface {
	isDataBinding_PattenFrom()
}

type DataBinding_FromArg struct {
	FromArg string `protobuf:"bytes,2,opt,name=from_arg,json=fromArg,proto3,oneof"` // from_arg 用于绑定参数路径，可支持字段名及路径，如参数或返回值处于较深路径时可使用 aa.bb.cc, * 表示使用整个 arg 作为参数
}

type DataBinding_FromResp struct {
	FromResp string `protobuf:"bytes,3,opt,name=from_resp,json=fromResp,proto3,oneof"` // from_resp 用于绑定参数路径，同 from_arg, 只是获取数据的来源为 resp
}

type DataBinding_FromContext struct {
	FromContext string `protobuf:"bytes,4,opt,name=from_context,json=fromContext,proto3,oneof"` // from_context 表示上下文中的信息，上下文为本次调用 context 中的 value 信息, 该字段为存放上下文数据的 KeY
}

type DataBinding_FromQuery struct {
	FromQuery string `protobuf:"bytes,5,opt,name=from_query,json=fromQuery,proto3,oneof"` // from_query 表示目标数据来自当前的数据库查询结果
}

func (*DataBinding_FromArg) isDataBinding_PattenFrom() {}

func (*DataBinding_FromResp) isDataBinding_PattenFrom() {}

func (*DataBinding_FromContext) isDataBinding_PattenFrom() {}

func (*DataBinding_FromQuery) isDataBinding_PattenFrom() {}

type isDataBinding_PattenTo interface {
	isDataBinding_PattenTo()
}

type DataBinding_ToArg struct {
	ToArg string `protobuf:"bytes,7,opt,name=to_arg,json=toArg,proto3,oneof"` // to_arg 用于绑定返回值路径, 说明需要将本次执行结果写入 args
}

type DataBinding_ToResp struct {
	ToResp string `protobuf:"bytes,8,opt,name=to_resp,json=toResp,proto3,oneof"` // to_resp 用于绑定返回值路径，说明需要将本次执行结果写入 resp
}

type DataBinding_ToContext struct {
	ToContext string `protobuf:"bytes,9,opt,name=to_context,json=toContext,proto3,oneof"` // to_context 用于绑定返回值路径，说明需要将本次执行结果写入 context, WARN: 暂不支持 - 需要找到一个支持类型推导的方式
}

func (*DataBinding_ToArg) isDataBinding_PattenTo() {}

func (*DataBinding_ToResp) isDataBinding_PattenTo() {}

func (*DataBinding_ToContext) isDataBinding_PattenTo() {}

type TableDefine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Index []*IndexDefine `protobuf:"bytes,1416,rep,name=index,proto3" json:"index,omitempty"`
}

func (x *TableDefine) Reset() {
	*x = TableDefine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableDefine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableDefine) ProtoMessage() {}

func (x *TableDefine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableDefine.ProtoReflect.Descriptor instead.
func (*TableDefine) Descriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{5}
}

func (x *TableDefine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableDefine) GetIndex() []*IndexDefine {
	if x != nil {
		return x.Index
	}
	return nil
}

type TableFindDefine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Where map[string]string      `protobuf:"bytes,1,rep,name=where,proto3" json:"where,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Page  *TableFindPagingDefine `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Query string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *TableFindDefine) Reset() {
	*x = TableFindDefine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_query_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableFindDefine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableFindDefine) ProtoMessage() {}

func (x *TableFindDefine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_query_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableFindDefine.ProtoReflect.Descriptor instead.
func (*TableFindDefine) Descriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{6}
}

func (x *TableFindDefine) GetWhere() map[string]string {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *TableFindDefine) GetPage() *TableFindPagingDefine {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *TableFindDefine) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type TableFindPagingDefine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *TableFindPagingDefine) Reset() {
	*x = TableFindPagingDefine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_query_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableFindPagingDefine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableFindPagingDefine) ProtoMessage() {}

func (x *TableFindPagingDefine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_query_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableFindPagingDefine.ProtoReflect.Descriptor instead.
func (*TableFindPagingDefine) Descriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{7}
}

func (x *TableFindPagingDefine) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TableFindPagingDefine) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type IndexDefine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Name string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *IndexDefine) Reset() {
	*x = IndexDefine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_query_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexDefine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDefine) ProtoMessage() {}

func (x *IndexDefine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_query_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDefine.ProtoReflect.Descriptor instead.
func (*IndexDefine) Descriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{8}
}

func (x *IndexDefine) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *IndexDefine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BindDefine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bind BindEnum_Bind `protobuf:"varint,1,opt,name=bind,proto3,enum=eden.common.BindEnum_Bind" json:"bind,omitempty"`
}

func (x *BindDefine) Reset() {
	*x = BindDefine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_query_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindDefine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindDefine) ProtoMessage() {}

func (x *BindDefine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_query_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindDefine.ProtoReflect.Descriptor instead.
func (*BindDefine) Descriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{9}
}

func (x *BindDefine) GetBind() BindEnum_Bind {
	if x != nil {
		return x.Bind
	}
	return BindEnum_None
}

type BindEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BindEnum) Reset() {
	*x = BindEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_query_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEnum) ProtoMessage() {}

func (x *BindEnum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_query_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEnum.ProtoReflect.Descriptor instead.
func (*BindEnum) Descriptor() ([]byte, []int) {
	return file_proto_common_query_proto_rawDescGZIP(), []int{10}
}

var file_proto_common_query_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*DataQuery)(nil),
		Field:         1424,
		Name:          "eden.common.crud",
		Tag:           "bytes,1424,opt,name=crud",
		Filename:      "proto/common.query.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*QueryChain)(nil),
		Field:         1425,
		Name:          "eden.common.chain",
		Tag:           "bytes,1425,opt,name=chain",
		Filename:      "proto/common.query.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*TableDefine)(nil),
		Field:         1415,
		Name:          "eden.common.table",
		Tag:           "bytes,1415,opt,name=table",
		Filename:      "proto/common.query.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*TableFindDefine)(nil),
		Field:         1416,
		Name:          "eden.common.find",
		Tag:           "bytes,1416,opt,name=find",
		Filename:      "proto/common.query.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*BindEnum_Bind)(nil),
		Field:         1417,
		Name:          "eden.common.bind",
		Tag:           "varint,1417,opt,name=bind,enum=eden.common.BindEnum_Bind",
		Filename:      "proto/common.query.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// crud 用来表示一个单独的 SQL 语句
	//
	// optional eden.common.DataQuery crud = 1424;
	E_Crud = &file_proto_common_query_proto_extTypes[0]
	// chain 用来表示一系列 SQL 逻辑，期间可插入自定义函数处理逻辑及各种自定义语句，在 Chain 中的代码将使用同一个事务
	//
	// optional eden.common.QueryChain chain = 1425;
	E_Chain = &file_proto_common_query_proto_extTypes[1]
	// optional eden.common.TableFindDefine find = 1416;
	E_Find = &file_proto_common_query_proto_extTypes[3]
	// optional eden.common.BindEnum.Bind bind = 1417;
	E_Bind = &file_proto_common_query_proto_extTypes[4]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional eden.common.TableDefine table = 1415;
	E_Table = &file_proto_common_query_proto_extTypes[2]
)

var File_proto_common_query_proto protoreflect.FileDescriptor

var file_proto_common_query_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x72, 0x65, 0x61, 0x6c,
	0x69, 0x62, 0x6f, 0x78, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x7e, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e,
	0x75, 0x6d, 0x22, 0x6d, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x15, 0x0a, 0x11, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x6e, 0x6a, 0x65, 0x63, 0x74,
	0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4f, 0x6e, 0x65, 0x10,
	0x06, 0x22, 0x43, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x36,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x72, 0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x45, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x12, 0x37, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x92, 0x0b,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0xf2, 0x01,
	0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x40, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x72, 0x65,
	0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x34, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x34, 0x0a, 0x04,
	0x72, 0x65, 0x73, 0x70, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72, 0x65, 0x61,
	0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x72, 0x65,
	0x73, 0x70, 0x22, 0xa8, 0x02, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x42, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61,
	0x72, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d,
	0x41, 0x72, 0x67, 0x12, 0x1d, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x23, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x66,
	0x72, 0x6f, 0x6d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x17, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x61,
	0x72, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x41, 0x72,
	0x67, 0x12, 0x19, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x06, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x0a,
	0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x09, 0x74, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x70, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x5f, 0x66, 0x72, 0x6f, 0x6d,
	0x42, 0x0b, 0x0a, 0x09, 0x70, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x5f, 0x74, 0x6f, 0x22, 0x5a, 0x0a,
	0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x37, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x88, 0x0b, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x44, 0x65, 0x66, 0x69,
	0x6e, 0x65, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0xe8, 0x01, 0x0a, 0x0f, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x12, 0x45, 0x0a,
	0x05, 0x77, 0x68, 0x65, 0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x72,
	0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x66, 0x69,
	0x6e, 0x65, 0x2e, 0x57, 0x68, 0x65, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x77,
	0x68, 0x65, 0x72, 0x65, 0x12, 0x3e, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x69,
	0x6e, 0x64, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x38, 0x0a, 0x0a, 0x57, 0x68,
	0x65, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x3f, 0x0a, 0x15, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x69, 0x6e,
	0x64, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x35, 0x0a, 0x0b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x44, 0x65,
	0x66, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x0a,
	0x42, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x62, 0x69,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x69,
	0x62, 0x6f, 0x78, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42,
	0x69, 0x6e, 0x64, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x62, 0x69,
	0x6e, 0x64, 0x22, 0x2a, 0x0a, 0x08, 0x42, 0x69, 0x6e, 0x64, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x1e,
	0x0a, 0x04, 0x42, 0x69, 0x6e, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x10, 0x01, 0x3a, 0x53,
	0x0a, 0x04, 0x63, 0x72, 0x75, 0x64, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x90, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x72, 0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x04, 0x63,
	0x72, 0x75, 0x64, 0x3a, 0x56, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1e, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x91, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x58, 0x0a, 0x05, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x87, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72,
	0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x52, 0x05,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x3a, 0x59, 0x0a, 0x04, 0x66, 0x69, 0x6e, 0x64, 0x12, 0x1e, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x46, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6e, 0x64,
	0x3a, 0x57, 0x0a, 0x04, 0x62, 0x69, 0x6e, 0x64, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x89, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x22, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x42,
	0x69, 0x6e, 0x64, 0x52, 0x04, 0x62, 0x69, 0x6e, 0x64, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x62, 0x6f, 0x78, 0x2e, 0x63, 0x6e, 0x2f,
	0x68, 0x75, 0x62, 0x76, 0x33, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x71, 0x6c, 0x2d, 0x66, 0x78, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_common_query_proto_rawDescOnce sync.Once
	file_proto_common_query_proto_rawDescData = file_proto_common_query_proto_rawDesc
)

func file_proto_common_query_proto_rawDescGZIP() []byte {
	file_proto_common_query_proto_rawDescOnce.Do(func() {
		file_proto_common_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_query_proto_rawDescData)
	})
	return file_proto_common_query_proto_rawDescData
}

var file_proto_common_query_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_common_query_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_common_query_proto_goTypes = []interface{}{
	(QueryTypeEnum_QueryType)(0),        // 0: eden.common.QueryTypeEnum.QueryType
	(BindEnum_Bind)(0),                  // 1: eden.common.BindEnum.Bind
	(*QueryTypeEnum)(nil),               // 2: eden.common.QueryTypeEnum
	(*DataQuery)(nil),                   // 3: eden.common.DataQuery
	(*QueryChain)(nil),                  // 4: eden.common.QueryChain
	(*DataMapping)(nil),                 // 5: eden.common.DataMapping
	(*DataBinding)(nil),                 // 6: eden.common.DataBinding
	(*TableDefine)(nil),                 // 7: eden.common.TableDefine
	(*TableFindDefine)(nil),             // 8: eden.common.TableFindDefine
	(*TableFindPagingDefine)(nil),       // 9: eden.common.TableFindPagingDefine
	(*IndexDefine)(nil),                 // 10: eden.common.IndexDefine
	(*BindDefine)(nil),                  // 11: eden.common.BindDefine
	(*BindEnum)(nil),                    // 12: eden.common.BindEnum
	nil,                                 // 13: eden.common.TableFindDefine.WhereEntry
	(*descriptorpb.MethodOptions)(nil),  // 14: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 15: google.protobuf.MessageOptions
}
var file_proto_common_query_proto_depIdxs = []int32{
	5,  // 0: eden.common.DataQuery.query:type_name -> eden.common.DataMapping
	5,  // 1: eden.common.QueryChain.query:type_name -> eden.common.DataMapping
	0,  // 2: eden.common.DataMapping.type:type_name -> eden.common.QueryTypeEnum.QueryType
	6,  // 3: eden.common.DataMapping.args:type_name -> eden.common.DataBinding
	6,  // 4: eden.common.DataMapping.resp:type_name -> eden.common.DataBinding
	10, // 5: eden.common.TableDefine.index:type_name -> eden.common.IndexDefine
	13, // 6: eden.common.TableFindDefine.where:type_name -> eden.common.TableFindDefine.WhereEntry
	9,  // 7: eden.common.TableFindDefine.page:type_name -> eden.common.TableFindPagingDefine
	1,  // 8: eden.common.BindDefine.bind:type_name -> eden.common.BindEnum.Bind
	14, // 9: eden.common.crud:extendee -> google.protobuf.MethodOptions
	14, // 10: eden.common.chain:extendee -> google.protobuf.MethodOptions
	15, // 11: eden.common.table:extendee -> google.protobuf.MessageOptions
	14, // 12: eden.common.find:extendee -> google.protobuf.MethodOptions
	14, // 13: eden.common.bind:extendee -> google.protobuf.MethodOptions
	3,  // 14: eden.common.crud:type_name -> eden.common.DataQuery
	4,  // 15: eden.common.chain:type_name -> eden.common.QueryChain
	7,  // 16: eden.common.table:type_name -> eden.common.TableDefine
	8,  // 17: eden.common.find:type_name -> eden.common.TableFindDefine
	1,  // 18: eden.common.bind:type_name -> eden.common.BindEnum.Bind
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	14, // [14:19] is the sub-list for extension type_name
	9,  // [9:14] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_common_query_proto_init() }
func file_proto_common_query_proto_init() {
	if File_proto_common_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_common_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTypeEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryChain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBinding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_query_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableDefine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_query_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableFindDefine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_query_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableFindPagingDefine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_query_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexDefine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_query_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindDefine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_query_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_common_query_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*DataBinding_FromArg)(nil),
		(*DataBinding_FromResp)(nil),
		(*DataBinding_FromContext)(nil),
		(*DataBinding_FromQuery)(nil),
		(*DataBinding_ToArg)(nil),
		(*DataBinding_ToResp)(nil),
		(*DataBinding_ToContext)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_query_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_query_proto_goTypes,
		DependencyIndexes: file_proto_common_query_proto_depIdxs,
		EnumInfos:         file_proto_common_query_proto_enumTypes,
		MessageInfos:      file_proto_common_query_proto_msgTypes,
		ExtensionInfos:    file_proto_common_query_proto_extTypes,
	}.Build()
	File_proto_common_query_proto = out.File
	file_proto_common_query_proto_rawDesc = nil
	file_proto_common_query_proto_goTypes = nil
	file_proto_common_query_proto_depIdxs = nil
}
